baseURL = "https://www.anttikivi.fi"
defaultContentLanguage = "fi"
defaultContentLanguageInSubdir = false
disableHugoGeneratorInject = true
title = "Antti Kivi"

[params]
  author = "Antti Kivi"
  copyrightYear = 2024
  images = ["opengraph-image.png"]
  title = "Antti Kivi"

[languages]
  [languages.fi]
    disabled = false
    # languageCode = "fi-FI"
    languageCode = "fi"
    languageName = "suomi"
    weight = 1
    [languages.fi.params]
      description = "Viestint채asiantuntija, yritt채j채 ja ylioppilas."
      subtitle = "Viestint채asiantuntija"
      switchTo = "Suomeksi"
[languages.en]
  disabled = false
  # languageCode = "en-GB"
  languageCode = "en"
  languageName = "English"
  weight = 2
  [languages.en.params]
    description = "Communications adviser, entrepreneur and student."
    subtitle = "Communications adviser"
    switchTo = "In English"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.121.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"
