name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') &&
      !startsWith(github.event.head_commit.message, 'docs')"
    strategy:
      matrix:
        node: ["20", "22"]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build the site
        run: npm run build

  check:
    name: Check
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') &&
      !startsWith(github.event.head_commit.message, 'docs')"
    strategy:
      matrix:
        node: ["20", "22"]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint the project
        run: npm run lint
